site_name: Docs
site_url: https://paretech.github.io/docs
theme:
  name: material
  logo: assets/paretech_logo.png
markdown_extensions:
  - pymdownx.saneheaders
  - mdx_truly_sane_lists:
      nested_indent: 2
