site_name: Paretech Docs
site_url: https://paretech.github.io/docs
theme:
  name: material
  logo: assets/paretech_logo.png
  features:
    - navigation.tabs
    - content.code.copy
markdown_extensions:
  - admonition
  - pymdownx.saneheaders
  - mdx_truly_sane_lists:
      nested_indent: 2
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
